name: jazzdesign
services:
  web:
    image: caddy:2-alpine
    restart: unless-stopped
    depends_on: [php]
    ports:
      - "127.0.0.1:3050:80"
    volumes:
      - ./site:/srv/site
      - ./Caddyfile:/etc/caddy/Caddyfile

  php:
    image: php:8.2-fpm-alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./site:/srv/site
